image: "node:latest"

stages:
  - build
  - deploy

build_app:
  stage: build
  script:
    - npm install
    - npm build
  artifacts:
    paths:
      - build
    expire_in: 1 day

deploy_draft:
  stage: deploy
  script:
    - npm install -g netlify-cli
    - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_TOKEN} --dir build

deploy_prod:
  stage: deploy
  script:
    - npm install -g netlify-cli
    - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_TOKEN} --dir build --prod
  when: manual
